id: I13A747CA
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T22:22:58.120869'
last_modified: '2022-06-18T22:22:58.120890'
parser: null
source_metadata:
  title: Jam dbyangs bsod nams rgyal mtshans (1563–1617) Sakya Genealogy
  author: འཇམ་དབྱངས་བསོད་ནམས་རྒྱལ་མཚན།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2018-09-06);
    revision in process, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Lobsang Gyaltsen, Dharamsala (lg)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/2303
  bases:
    497d:
      title: Jam dbyangs bsod nams rgyal mtshans (1563–1617) Sakya Genealogy
      order: 1
      base_file: 497d.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
